name: 'publish-forge'
description: 'GitHub Action to publish an Autodesk Forge App Bundle'
author: 'zahmadsaleem'
inputs:
  client_id:
    required: true
    description: 'Forge Client ID'
  client_secret:
    required: true
    description: 'Forge Client Secret'
  appbundle_id:
    required: true
    description: 'Forge AppBundle Id/Name'
  appbundle_engine:
    required: true
    description: 'Forge AppBundle engine'
  appbundle_alias:
    required: false
    default: '$LATEST'
    description: 'Forge AppBundle alias'
  appbundle_path:
    required: true
    description: 'Path to the AppBundle zip file'
  activities:
    required: true
    description: 'File path selector to the activities json file(s)'
  create:
    required: false
    description: 'Create if not exists'

runs:
  using: 'node16'
  main: 'dist/index.js'
