name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          npm install
      - run: |
          npm run all

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          clientId : ${{ secrets.FORGE_CLIENT_ID }}
          clientSecret:  ${{ secrets.FORGE_CLIENT_SECRET }}
          activities: "./testdata/*.activity.json"
          appBundleEngine: "Autodesk.Revit+2023"
          appBundlePath: "./testdata/AppBundle.bundle.zip"
          appBundleId: "TestAppBundle"
          appBundleAlias: "prod"
          create: true

